VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Docs"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public docsSlNo As Long
Public docsTitle As String
Public docsDescription As String
Public docsLink As String
Public docsType As String

Public Sub class_initialize()
    
End Sub


