VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Tasks"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public taskSlNo As Long
Public taskType As String
Public taskAssigned As String
Public taskTitle As String
Public taskDescription As String
Public taskStatus As String
Public taskStartTime As Date
Public taskCompletedTime As Date
Public taskDays As Integer



Public Sub class_initialize()
    
End Sub

